# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VTynS5LaAyz+edTdY7WdWsv8k8OHc0+mFCSzJiGgHay+tqwUYOAtbTZAUrBSHi6WX6QyCW/dV1QP9+H07ovW8Lqvt1P4YHmDZjfFZZ9ca48rpa0F5jQNB/Wt+9nNXMd0xtqxjqdQo9hFtcFRUECeRM9iCr5Li6XXiBSB8GZtMn0R27NxETnYlFmkfFMrYHXyRVM+EmG1gXE5DJx51qd9qe9CwjqtfA7/yfZqKd5dLbq0qJamIksRTurUZQYXxZ/xRk7b1ucB4NvZdIjckNUJd+vasJe67iMFa7NIHaRgNWSuzapvX5h/mvQSwL6FWZLH0EpSfkxr93m+sJDyfB1joQGCHrBx58Vz8GbwLXSyVtOm/IVgTH6QwTu+6dVdHFrsfJsdG+OoWuqlMNagxy275S2MHWOhX0JpP73n4A1iTXqz9Iq8p8Ofvd8DTcpgAZQQgYjl7K3FRLH9yorBEl8OIcS4m3Z9qWxDWuhBRjvdk/1nqvJUHFTXroD0/JcQaopAKinyz5C2kOEIqr7mDwfSzhZ6/PXuSWywH+D1DO4tzXquK3852PG4/enNKnx3Oq3ZJ2nUmVEqhMriKmad4/9Ow8r+vqrgxGfEUc6OLFy1oERwbrOXHCnhXcd/O6aouNEErGf3Twr4Jg3c0tvIGd4aVx7Mf5CLETFPmZ1N6U3HJd0="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - tree
      - libconfuse-dev
  coverity_scan:
    project:
      name: "troglobit/mini-snmpd"
      description: "A minimal SNMP agent implementation"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make clean all"
    branch_pattern: dev

# Override default build command, we do not have `make test` yet
script:
  - ./autogen.sh
  - ./configure --prefix=/
  - make clean
  - make -j5 all
  - DESTDIR=/tmp/ make install-strip
  - tree /tmp
  - make distcheck

